=== mkirchmann/pmquiz/de.neuenberger.pmp.processes/src/main/resources/processGroups.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2007 rel. 3 sp1 (http://www.altova.com) von Janine Porrmann (PRODYNA GmbH) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PMP_Processes" type="cplxProcessGroups">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="cplxProcessGroups">
		<xs:sequence>
			<xs:element name="KnowledgeArea" type="cplxKnowledgeArea" maxOccurs="unbounded"/>
			<xs:element name="ProcessGroup" type="cplxProcessGroup" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cplxProcessGroup">
		<xs:complexContent>
			<xs:extension base="cplxNamed">
				<xs:sequence>
					<xs:element name="Process" maxOccurs="unbounded">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="cplxProcess">
									<xs:attribute name="knowledgeAreaId" type="xs:string"/>
								</xs:extension>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="cplxProcess">
		<xs:complexContent>
			<xs:extension base="cplxNamed"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="cplxNamed">
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="cplxKnowledgeArea">
		<xs:complexContent>
			<xs:extension base="cplxNamed">
				<xs:sequence>
					<xs:element name="Process" type="cplxProcess"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="Addition" type="cplxAddition" maxOccurs="1" minOccurs="0"></xs:element>
				</xs:sequence>
				<xs:attribute name="id" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="cplxAddition">

		<xs:sequence>
			<xs:element name="Group" type="cplxGroup" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cplxGroup">
		<xs:complexContent>
			<xs:extension base="cplxNamed">
				<xs:sequence>
					<xs:element name="Definition" type="cplxDefinition" maxOccurs="unbounded" minOccurs="4"></xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="cplxDefinition">
		<xs:complexContent>
			<xs:extension base="cplxNamed">
				<xs:attribute name="description" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== mkirchmann/pmquiz/de.neuenberger.pmp.processes/bin/de/neuenberger/pmp/processes/pmp_processes.xml
<?xml version="1.0" encoding="UTF-8"?>
<PMP_Processes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\mkirchmann\processGroups.xsd">
<KnowledgeArea id="IM" name="Integration Management"/>
<KnowledgeArea id="ScopM" name="Scope Management"/>
<KnowledgeArea id="TimM" name="Time Management"/>
<KnowledgeArea id="CostM" name="Cost Management"/>
<KnowledgeArea id="QM" name="Quality Management"/>
<KnowledgeArea id="HRM" name="Human Resource Management"/>
<KnowledgeArea id="ComM" name="Communications Management"/>
<KnowledgeArea id="RiskM" name="Risk Management"/>
<KnowledgeArea id="ProcM" name="Procurement Management"/>
<KnowledgeArea id="StakM" name="Stakeholder Management"/>
	<ProcessGroup name="Initiating">
		<Process name="Select Project Manager" knowledgeAreaId="IM"/>
		<Process name="Determine Company Culture and Existing Systems" knowledgeAreaId="IM"/>
		<Process name="Collect Processes, procedures, and historical information" knowledgeAreaId="IM"/>
		<Process name="Divide large projects into phases" knowledgeAreaId="IM"/>
		<Process name="Understand the business case" knowledgeAreaId="IM"/>
		<Process name="Uncover initial requirements, assumptions, risks, constaints and existing agreements" knowledgeAreaId="IM"/>
		<Process name="Assess project and product feasibility within the given constraints" knowledgeAreaId="IM"/>
		<Process name="Create measurable objectives" knowledgeAreaId="IM"/>
		<Process name="Develop project charter" knowledgeAreaId="IM"/>
		<Process name="Identify Stakeholders and determine their expectations, influence and impact" knowledgeAreaId="StakM"/>
	</ProcessGroup>
	<ProcessGroup name="Planning">
		<Process name="Determine how you will plan for each knowledge area" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,HRM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Determine detailed requirements" knowledgeAreaId="ScopM"/>
		<Process name="Create Project scope statement" knowledgeAreaId="ScopM"/>
		<Process name="Assess what to purchase and create procurement documents" knowledgeAreaId="ProcM"/>
		<Process name="Determine planning team" knowledgeAreaId="IM,HRM"/>
		<Process name="Create WBS and WBS dictionary" knowledgeAreaId="ScopM"/>
		<Process name="Create Activity List" knowledgeAreaId="TimM"/>
		<Process name="Create Network Diagram" knowledgeAreaId="TimM"/>
		<Process name="Estimate resource requirements" knowledgeAreaId="TimM"/>
		<Process name="Estimate time and cost" knowledgeAreaId="TimM,CostM"/>
		<Process name="Determine critical path" knowledgeAreaId="TimM"/>
		<Process name="Develop schedule" knowledgeAreaId="TimM"/>
		<Process name="Develop budget" knowledgeAreaId="CostM"/>
		<Process name="Determine quality standards, processes, and metrics" knowledgeAreaId="QM"/>
		<Process name="Create process improvement plan" knowledgeAreaId="QM"/>
		<Process name="Determine all roles and responsibilities" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,HRM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Plan communications and stakeholder engagement" knowledgeAreaId="ComM,StakM"/>
		<Process name="Perform risk identification, qualtitative risk analysis, and risk response planning" knowledgeAreaId="RiskM"/>
		<Process name="Go back - iterations" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,HRM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Finalize procurement documents" knowledgeAreaId="ProcM"/>
		<Process name="Create change management plan" knowledgeAreaId="IM"/>
		<Process name="Finalize the &quot;how to execute and control&quot; part of all management plans" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,HRM,CostM,RiskM,ProcM,StakM"/>
		<Process name="Develop realistic and final PM plan and performance measurement baseline" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,HRM,CostM,RiskM,ProcM,StakM"/>
		<Process name="Gain formal approval of the plan" knowledgeAreaId="IM"/>
		<Process name="Hold Kickoff meeting" knowledgeAreaId="IM"/>
	</ProcessGroup>
	<ProcessGroup name="Executing">
		<Process name="Execute the work according to the PM plan" knowledgeAreaId="IM"/>
		<Process name="Produce product deliverables (product scope)" knowledgeAreaId="IM"/>
		<Process name="Gather work performance data" knowledgeAreaId="IM"/>
		<Process name="Request changes" knowledgeAreaId="IM,QM,HRM,ProcM,StakM"/>
		<Process name="Implement only approved changes" knowledgeAreaId="IM"/>
		<Process name="Continuously improve" knowledgeAreaId="IM,QM"/>
		<Process name="Follow process" knowledgeAreaId="IM,QM"/>
		<Process name="Determine whether processes are correct and effective (quality assurance)" knowledgeAreaId="QM"/>
		<Process name="Perform quality audits" knowledgeAreaId="QM"/>
		<Process name="Acquire final team" knowledgeAreaId="HRM"/>
		<Process name="Manage people" knowledgeAreaId="HRM"/>
		<Process name="Evaluate team and individual performance" knowledgeAreaId="HRM"/>
		<Process name="Hold team building activities" knowledgeAreaId="HRM"/>
		<Process name="Give recognition and rewards" knowledgeAreaId="HRM"/>
		<Process name="Use issue logs" knowledgeAreaId="HRM"/>
		<Process name="Facilitate conflict resolution" knowledgeAreaId="HRM"/>
		<Process name="Release resources as work is completed" knowledgeAreaId="HRM"/>
		<Process name="Send and receive information, and solicit feedback" knowledgeAreaId="ComM"/>
		<Process name="Report on project performance" knowledgeAreaId="ComM"/>
		<Process name="Manage stakeholder engagement and expectations" knowledgeAreaId="StakM"/>
		<Process name="Hold Meetings" knowledgeAreaId="IM,ComM"/>
		<Process name="Select sellers" knowledgeAreaId="ProcM"/>
	</ProcessGroup>
	<ProcessGroup name="Monitoring and Controlling">
		<Process name="Take action to control the project" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Measure performance against the performance measurement baseline" knowledgeAreaId="IM,ScopM,TimM,CostM"/>
		<Process name="Measure performance against the other metrics in the PM plan" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,CostM,RiskM,ProcM,StakM"/>
		<Process name="Analyze and evaluate performance" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Determine if variances warrant a corrective action or other change request" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Influence the factors that cause changes" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Request changes" knowledgeAreaId="IM,ScopM,TimM,CostM,QM,ComM,RiskM,ProcM,StakM"/>
		<Process name="Perform integrated change control" knowledgeAreaId="IM"/>
		<Process name="Approve or reject changes" knowledgeAreaId="IM"/>
		<Process name="Update the PM plan and project documents" knowledgeAreaId="IM,TimM,CostM,ComM,ProcM"/>
		<Process name="Inform stakeholders of the results of change requests" knowledgeAreaId="IM,ComM,StakM"/>
		<Process name="Monitor stakeholder engagement" knowledgeAreaId="StakM"/>
		<Process name="Manage configuration" knowledgeAreaId="IM"/>
		<Process name="Create forecasts" knowledgeAreaId="TimM,CostM"/>
		<Process name="Gain acceptance of interim deliverables from the customer" knowledgeAreaId="ScopM"/>
		<Process name="Perform quality control" knowledgeAreaId="QM"/>
		<Process name="Perfom risk reasssessments and audits" knowledgeAreaId="RiskM"/>
		<Process name="Manage reserves" knowledgeAreaId="RiskM"/>
		<Process name="Control procurements" knowledgeAreaId="ProcM"/>
	</ProcessGroup>
	<ProcessGroup name="Closing">
		<Process name="Confirm work is done to requirements" knowledgeAreaId="IM,ProcM"/>
		<Process name="Complete procurement closure" knowledgeAreaId="ProcM"/>
		<Process name="Gain final acceptance of the product" knowledgeAreaId="IM"/>
		<Process name="Complete financial closure" knowledgeAreaId="IM"/>
		<Process name="Hand off completed product" knowledgeAreaId="IM"/>
		<Process name="Solicit feedback from the customer about the project" knowledgeAreaId="IM"/>
		<Process name="Complete final performance reporting" knowledgeAreaId="IM"/>
		<Process name="Index and archive records" knowledgeAreaId="IM,ProcM"/>
		<Process name="Gather final lessons learned and update knowledge base" knowledgeAreaId="IM,ProcM"/>
	</ProcessGroup>
</PMP_Processes>
